language: node_js

node_js:
- 6
- 8
- 10

install:
  - npm install --global npm
  - npm --version
  - npm ci

matrix:
  fast_finish: true

notifications:
  email: false

cache:
  directories:
  - "$HOME/.npm"
